@startuml

title __API's Class Diagram__\n

  namespace com.taodongdong.ecommerce {
    namespace api {
      abstract class com.taodongdong.ecommerce.api.AbstractApiClient {
          {static} + RPC_ENTRY : String
          {static} # JSONType : MediaType
          # okHttpClient : OkHttpClient
          # token : String
          + AbstractApiClient()
          {abstract} + onIOException()
          {abstract} + onRequestJSONException()
          {abstract} + onResponseFormatInvalid()
          {abstract} + onResponseJSONException()
          # forAction()
          # sendRequest()
          # sendRequest()
          # sendRequest()
          # setToken()
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      interface com.taodongdong.ecommerce.api.ApiCallback {
          {abstract} + onError()
          {abstract} + onSuccess()
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.ApiClient {
          # context : Context
          + ApiClient()
          + approveMerchant()
          + confirmOrder()
          + createOrder()
          + createProduct()
          + getMyStoreInfo()
          + getProductInfo()
          + getUserInfo()
          + isRegistered()
          + login()
          + logout()
          + modifyProduct()
          + onIOException()
          + onRequestJSONException()
          + onResponseFormatInvalid()
          + onResponseJSONException()
          + payOrder()
          + register()
          + searchProducts()
          + sendOrder()
          + setUpStore()
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.Errors {
          {static} + ALREADY_HAVE_STORE : int
          {static} + ALREADY_LOGIN : int
          {static} + ALREADY_MERCHANT : int
          {static} + ALREADY_REGISTERED : int
          {static} + AUTHORITY_ERROR : int
          {static} + CANT_CREATE_HASH : int
          {static} + INVALID_AUTHORITY_TO_MERCHANT : int
          {static} + INVALID_STATUS : int
          {static} + NOT_LOGIN : int
          {static} + NOT_MERCHANT : int
          {static} + NOT_OWNER_MERCHANT : int
          {static} + NOT_OWNER_PURCHASER : int
          {static} + NO_ENOUGH_MONEY : int
          {static} + NO_STORE : int
          {static} + NO_SUCH_ORDER : int
          {static} + NO_SUCH_PRODUCT : int
          {static} + NO_SUCH_STORE : int
          {static} + NO_SUCH_USER : int
          {static} + PASSWORD_ERROR : int
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.OrderInfo {
          {static} + STATUS_CONFIRMED : int
          {static} + STATUS_UNDELIVERED : int
          {static} + STATUS_UNPAID : int
          {static} + STATUS_UNSENT : int
          + id : int
          + merchantUserId : int
          + orderStatus : int
          + productAmount : int
          + productDescription : String
          + productId : int
          + productImage : String
          + productName : String
          + productPrice : int
          + purchaserUserId : int
          + storeId : int
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.Page {
          + currentPage : int
          + data : T[]
          + lastPage : int
          + perPage : int
          + total : int
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.ProductInfo {
          + id : int
          + productAmount : int
          + productDescription : String
          + productImage : String
          + productName : String
          + productPrice : int
          + storeId : int
          + getProductPriceReadable()
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.StoreInfo {
          + id : int
          + merchantUserId : int
          + storeName : String
      }
    }
  }
  

  namespace com.taodongdong.ecommerce {
    namespace api {
      class com.taodongdong.ecommerce.api.UserInfo {
          + authority : int
          + balance : int
          + id : int
          + username : String
      }
    }
  }
  

  com.taodongdong.ecommerce.api.ApiClient -up-|> com.taodongdong.ecommerce.api.AbstractApiClient


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
